@startuml
skinparam classAttributeIconSize 0

package yeonatano.steganography_system {
  
  interface AppShellConfigurator {
  }

  class AppConfig <<@Push>> {
  }
  
  AppShellConfigurator <|.. AppConfig
}
@enduml