@startuml

package "משתמש אורח (Guest)" {
    rectangle LoginView
    rectangle RegisterView
}

package "משתמש מחובר (Logged In)" {
    rectangle "MainLayout (סרגל הניווט)" as NavBar
    
    rectangle HomeView
    rectangle StegnoView
    rectangle HistoryView
    rectangle InboxView
    rectangle SentMessagesView

    rectangle NewMessageDialog
    rectangle FullTextDialog
    rectangle ConfirmDeleteDialog
}

' --- הרשמה, כניסה ויציאה ---
RegisterView --> LoginView
LoginView --> HomeView 
NavBar --> LoginView 

' --- סרגל הניווט (דו-כיווני לכל המסכים הפנימיים) ---
NavBar <--> HomeView
NavBar <--> StegnoView
NavBar <--> HistoryView
NavBar <--> InboxView
NavBar <--> SentMessagesView


' --- ניווט ישיר מכפתורי מסך הבית אל שאר המסכים ---
HomeView --> StegnoView
HomeView --> HistoryView
HomeView --> InboxView
HomeView --> SentMessagesView
HomeView --> RegisterView

' --- חלונות קופצים (נפתחים מהמסך ונסגרים חזרה אליו) ---
InboxView <--> NewMessageDialog
SentMessagesView <--> NewMessageDialog

InboxView <--> FullTextDialog

HistoryView <--> ConfirmDeleteDialog

@enduml