######################## SETUP application.properties ########################

## General setup
server.port = 8080
vaadin.launch-browser = true

## Terminal setup - text color, formating, disable logging... 
spring.output.ansi.enabled = always  
logging.pattern.console = %cyan(%d{HH:mm:ss}) [%green(%level)]  %cyan(%msg%n)
logging.level.root = ERROR

## Files Uploading setup
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 16MB
spring.servlet.multipart.max-request-size = 16MB

## MongoDB setup connection
spring.data.mongodb.uri=mongodb+srv://user:123123123@cluster0.fwitxup.mongodb.net/DB
#############################################################################

cloudconvert.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYmRmZTZmYWM0OTA0YjYxNGMyM2UzNDJkOWJjMDRhNWRiMzVhNDJhNzZjZTc0ZjExMjhlYjA0NWIzYjlkYTRkOGUxNDczMTQzMzA0YmJjMWMiLCJpYXQiOjE3Nzk4Mzk4MTEuMjg1NTM5LCJuYmYiOjE3Nzk4Mzk4MTEuMjg1NTQsImV4cCI6NDkzNTUxMzQxMS4yODA3MjIsInN1YiI6Ijc1NTU1OTYyIiwic2NvcGVzIjpbInVzZXIucmVhZCIsInVzZXIud3JpdGUiLCJ0YXNrLnJlYWQiLCJ0YXNrLndyaXRlIiwid2ViaG9vay5yZWFkIiwid2ViaG9vay53cml0ZSIsInByZXNldC5yZWFkIiwicHJlc2V0LndyaXRlIl19.p_dM0LnFOFU7ZdLTn4-oLod3UO3tv2Nhjjt4-hCNkE48_Fp68VA44OrqLkKcpr57uprywgBQ8oenkXZZkIU_2J_I3TtCZHE75PGPMPSwJIgKUwbzxIVbmtmOFCDhbF8F3_pkMd-ybzeozVGjbhaB6qxM90x5iFPSzs10egff6eTDzNdyLaKHqwT16u1mIYn6hIN2kYIw4XeyDXi8RJmbPGylL9JroKJM8k6I1gXZOUs3D7KsTx-_vV8OqwxrnVzDhROENktlmFgpaTOaIup2aS9O45wtW_DU6Zu5KzdZWqHs8haZ2ulktbSE4CcnjsOX2NjDx2VDvAQZUyOF5oZWJq-x9zuElAZAjcG1MGgvCBs3fYKZjjuFHJiu_eSkjO--4Cj__-XlNEVQzHi8KTyi-O-hakXMissgF4zRaU4AB7Oe5nYsyRwpvSHiTzyk6liRh3L8pepuQuIPSTc8i8SzD9xV2wLdJstOHUNlKgYUCy4EuJNmiW55IcqwTYYFcSVtjQzp58uh9rivRsj9HfmIyHSrC1taJTMW1yFKAFP-ozLeyZ5lAMlu3xPGXfMT0PL7t0qdvzthWeH31pu7QLXxdxyXPBsL8mkuN1zO0khQ2Jk96DCyljVTX9_WYcl2dVD-sQ6tDtN5DhKguuzx0ETk9O8PRUqdZISsRXQLr-bij4M
